name: AddonTemplate
version: '${project.version}'
api-version: '1.20.1'
main: com.author.addontemplate.AddonTemplate
softdepend: [Skript]
authors: [Yourself]
description: A template for a java maven skript addon
